language: go

go:
- 1.11.x
- master

go_import_path: github.com/NathanielRose/bedrock

before_install:
- echo $clientID
- echo $clientSecret
- echo $publicKey
- echo publicKey
- wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
- unzip terraform_0.11.11_linux_amd64.zip
- mkdir -p ${HOME}/bin ; export PATH=${PATH}:${HOME}/bin; mv terraform ${HOME}/bin/
- sudo apt-get install apt-transport-https lsb-release software-properties-common dirmngr -y
- AZ_REPO=$(lsb_release -cs)
- echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
- sudo apt-key --keyring /etc/apt/trusted.gpg.d/Microsoft.gpg adv --keyserver packages.microsoft.com --recv-keys BC528686B50D79E339D3721CEB3E94ADBE1229CF
- sudo apt-get update
- sudo apt-get install azure-cli
- curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
- echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
- sudo apt-get install -y kubectl
- curl https://raw.githubusercontent.com/helm/helm/master/scripts/get > get_helm.sh
- chmod 700 get_helm.sh
- ./get_helm.sh
- az -v
- terraform -v
- cp .netrc ~/.netrc
- chmod 600 ~/.netrc

script: go test -v  ./... -timeout 99999s




